remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md


title: "Tech Talk Replay" 
description: "Replay the Insights: Tech Talks Worth Watching"



